allowBuilds:
  '@google/genai': false
  esbuild: true
  msw: true
  protobufjs: false
minimumReleaseAgeExclude:
  - cron-parser@5.7.0
  - '@anthropic-ai/claude-agent-sdk-darwin-arm64@0.3.283'
  - '@anthropic-ai/claude-agent-sdk-darwin-x64@0.3.283'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64-musl@0.3.283'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64@0.3.283'
  - '@anthropic-ai/claude-agent-sdk-linux-x64-musl@0.3.283'
  - '@anthropic-ai/claude-agent-sdk-linux-x64@0.3.283'
  - '@anthropic-ai/claude-agent-sdk-win32-arm64@0.3.283'
  - '@anthropic-ai/claude-agent-sdk-win32-x64@0.3.283'
  - '@anthropic-ai/claude-agent-sdk@0.3.283'
packageExtensions:
  react-router@7.18.2:
    peerDependencies:
      '@types/react': ^19.2.18
packages:
  - apps/*
